name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: docker-token
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: zjslqshqz
        password: ${{ secrets.LOGIN_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        platforms: linux/amd64,linux/arm64
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        file: ./php-fpm
        push: true
        tags: zjslqshqz/php:test
