name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v3
      
    - name: go to php-fpm
      run: cd ./php-fpm
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        platforms: linux/amd64,linux/arm64
    - name: test
      run: ls
