name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      buildArtifact:
        description: 'choice build artifact'
        required: true
        type: choice
        options:
        - php-fpm@8.3.11
        - php-fpm-dev@7.4.33
        - php-fpm@7.4.33
        - php-fpm-dev@5.6
        - php-fpm@5.6
        - php-local@7.4.33
        - node
      imagesRepositoryName:
        description: 'choice images repository name'
        required: true
        type: choice
        options:
        - php
        - node
      tags:
        description: 'set images tags'
        default: 'latest'
        required: true

jobs:

  build:
    environment: docker-token
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: zjslqshqz
        password: ${{ secrets.LOGIN_TOKEN }}
        
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./${{ inputs.buildArtifact }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: zjslqshqz/${{ inputs.imagesRepositoryName }}:${{ inputs.tags }}
